name: mess_menu
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  awesome_notifications: ^0.7.4+1  
  intl: ^0.17.0
  flutter_launcher_icons: "^0.9.2"
  # permission_handler: ^8.2.2
  # flutter_local_notifications: ^13.0.0
  # permission_handler: ^10.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/menu_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

